### ISSUE TITLE
dev, test and production database configuration?

### ISSUE THREAD

**Issue by mickgardner** [vattle/sqlboiler#105]
A quick question: for the sqlboiler.yaml file, how do I (or is it even necessary - perhaps I'm misunderstanding), do a development, test and production database configuration?

**Comment by aarondl** [comment]
SQLBoiler's job is to generate models at development time. After the generation is done, it doesn't actually connect to the database for you and so SQLBoiler configuration is not necessary after that. That's to say test/production scenarios don't need to be covered.

It's up to your app to read in the parameters you need, connect to the database, and pass that into SQLBoiler. The interface it looks for is this:
https://godoc.org/github.com/vattle/sqlboiler/boil#Executor

How to pass the connection in is shown here:
https://github.com/vattle/sqlboiler#function-variations

Every function in SQLBoiler (in your generated models) takes a db parameter that is the executor interface. So you just pass your db in everywhere. Alternatively there's a G variant (as shown above) that allows you to use a globally set database handle.

A screencast that shows the general development flow is here:
https://github.com/vattle/sqlboiler#getting-started
You'll notice that when I run my app, I simply provide the connection string to `sql.Open` like you would do in any other app.

Hope that helps.

**Comment by mickgardner** [comment]
Thank you so much for that helpful and informative write up.
