### ISSUE TITLE
panic: sql: Register called twice for driver mysql

### ISSUE THREAD

**Issue by nati** [vattle/sqlboiler#115]
### What version of SQLBoiler are you using (`sqlboiler --version`)?
SQLBoiler v2.1.7

### Further information. What did you do, what did you expect?

when I run test with mysql, I got this error

"panic: sql: Register called twice for driver mysql"

This is imports in main_test.go

``` go
import (
	"bytes"
	"database/sql"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"os/exec"
	"strings"

	_ "github.com/go-sql-driver/mysql" 
	"github.com/pkg/errors"
	"github.com/spf13/viper"
	"github.com/vattle/sqlboiler/bdb/drivers"
	"github.com/vattle/sqlboiler/randomize"
)
```

You can see both of github.com/go-sql-driver/mysql and "github.com/vattle/sqlboiler/bdb/drivers" is imported in main_test.
mysql driver has also imported in 
https://github.com/vattle/sqlboiler/blob/master/bdb/drivers/mysql.go#L9

so how about remove this import from main_test.go ?

**Comment by aarondl** [comment]
Hey @nati, this doesn't happen to us and we run mysql tests all the time. Are you vendoring pieces of sqlboiler or the mysql drivers library? Just trying to understand what's going on here.

An import should only occur once in Go even if it's referenced many times. The only exception to this is when you start vendoring things and then things become different packages (even if they're byte-comparison same).

Tested with:
```text
├── main.go (imports both oneimport, and twoimport)
├── oneimport
│   └── lib.go  (init prints)
└── twoimport
    └── lib.go    (imports oneimport, init prints)
```

```text
loading oneimport
loading twoimport
{} {{}}
```

As you can see, despite oneimport being referenced twice, it's `init()` only ran once. Can you describe in more detail what your GOPATH/vendoring setup looks like?

**Comment by nati** [comment]
@aarondl  Thank you for your quick response.

Yes. both of libs are in vendor directory. (i'm using govendor)
The structure looks like this

vendor/github.com/go-sql-driver/mysql
vendor/vattle/sqlboiler

I believe "vendor/github.com/go-sql-driver/mysql should be used everytime in the my code path..

Anyway,  It looks like this isn't issue in SQLBoiler project. 
Thank you for your help on this.
