### ISSUE TITLE
Add option to use database's UTC time for updated_at and created_at instead of Go's time.Now

### ISSUE THREAD

**Issue by michael-younkin** [vattle/sqlboiler#126]
I think the built-in support for automatically handling columns named `updated_at` and `created_at` is great, except it uses the clocks on machines running the Go app, which can be out of sync with the clock on the database server. In distributed environments with many machines running the Go app, this could lead to errors that are difficult to correct.

So, instead of retrieving the current time using `time.Now()` and then sending that to the database, it would be great if we could optionally have SQLBoiler automatically insert a SQL function like `UTC_TIMESTAMP()` and have the database insert the current time instead of Go.

Most people probably won't care about this, which is why IMO it should be optional. It still doesn't provide any guarantees about the clock being monotonically increasing or anything like that. But I've seen cases where servers were a few hours or more off from the others due to a misconfigured NTP daemon. If it's the database server that has the problem, then it's easy to detect and fix because every record will be incorrect, but if it's 1 out of a dozen app servers that's wrong, then, even if you notice the problem, you probably won't ever be able to correct it.

**Comment by aarondl** [comment]
We talked about this and we basically feel that it's a use case that's trying to correct for mistakes in other systems. If you use Ansible/Salt/Chef/Cloudinit to correctly configure a machine these sorts of things shouldn't/don't happen. Hence we probably won't any time into it but I wouldn't reject a clean PR for it so long as it was indeed optional.

**Comment by michael-younkin** [comment]
Alright, thanks for the quick response. The tools you mentioned don't cover every possible failure case, and they aren't always usable. I agree that in a perfect world this would not be a problem, but when it comes to data integrity it's better to code defensively, especially when it's cheap in the common case. I may implement it if I end up deciding to use SQLBoiler.
