### ISSUE TITLE
MSSQL Tests Failing

### ISSUE THREAD

**Issue by aarondl** [vattle/sqlboiler#135]
https://circleci.com/gh/vattle/sqlboiler/525

@nemec784 Do you have any idea why this might be happening? I'm not sure how the tests pass for you and not for CI atm.

**Comment by nullbio** [comment]
@nemec784 Had a chance to look at this? Thanks.

**Comment by nemec784** [comment]
Sorry, i was on vacation.

I managed to reproduce this situation. Need to set `READ_COMMITTED_SNAPSHOT` option to `ON` right after `CREATE DATABASE` statement:

**mssql_main.tpl**
```go
func (m *mssqlTester) createTestDB() error {
	sql := fmt.Sprintf(`
	CREATE DATABASE %s;
	GO
	ALTER DATABASE %[1]s
	SET READ_COMMITTED_SNAPSHOT ON;
	GO`, m.testDBName)
	return m.runCmd(sql, "sqlcmd", "-S", m.host, "-U", m.user, "-P", m.pass)
}
```
After that, all tests pass each time:
```sh
PS D:\tmp\mssql> go test -race -run TestInsert -count 100 ./...
ok      _/D_/tmp/mssql  21.565s
```

In which branch need to push this changes, **dev** or **mssql_tests**?

**Comment by aarondl** [comment]
mssql_tests is the branch I'm doing the CI in. It's done and as soon as these pass I'm going to release this as a new major version!

Thanks for looking into it. I'll be dealing with Sqlboiler tonight
