### ISSUE TITLE
Test of generated models fails, probably because db user does not have permission to create a new db

### ISSUE THREAD

**Issue by lyoshenka** [vattle/sqlboiler#145]
Model generation worked fine. Then when I went to test the models:

```
$ sqlboiler --version
SQLBoiler v2.3.0
$ go test -v ./models/
failed running: mysql [--defaults-file=/tmp/optionfile816793928]

ERROR 1044 (42000) at line 1: Access denied for user 'boileruser'@'127.0.0.1' to database 'dedwqojajjmrsqkyrcnepxvwyyonfprzmnbhwzkz'
```

I think this happens because `boileruser` does not have permissions to create a new database or access it.

**Comment by lyoshenka** [comment]
I confirmed that `GRANT ALL ON dedwqojajjmrsqkyrcnepxvwyyonfprzmnbhwzkz.* to boileruser@127.0.0.1` fixes the error.

**Comment by nullbio** [comment]
Cool, glad to see you sorted it. You're correct though, those permissions are required.
