### ISSUE TITLE
Select operator does not work as expected with one-to-many relationships

### ISSUE THREAD

**Issue by sadu99** [vattle/sqlboiler#159]
### What version of SQLBoiler are you using?
SQLBoiler v2.4.0

### Issue
Certain columns can be currently selected using the `qm.select()` operator. However, when querying one-to-many relationships, all columns are selected regardless of the fields passed-in using the `qm.select()` operator.

### If this happened at runtime what code produced the issue? 
The following code can be found in the generated models that causes this issue:

```go
	queryMods := []qm.QueryMod{
		qm.Select("\"a\".*"),
	}

	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}
```

As seen above, `a.*` is added to the `QueryMod` slice regardless of the passed-in `mods`. 

### Possible Fix
The generated models could contain the following code to make this work:

```go
        queryMods := []qm.QueryMod{}
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	} else {
		queryMods = append(queryMods, qm.Select("\"a\".*"))
	}
```

Please let me know if the above is sufficient to understand the issue.

**Comment by aarondl** [comment]
Fixed on dev branch. Thanks for the report.

**Comment by sadu99** [comment]
Thanks for the quick response @aarondl I have tested on dev branch and confirmed the issue is fixed 😄  When will a release be made?

**Comment by aarondl** [comment]
@sadu99 Released :)

**Comment by sadu99** [comment]
@aarondl Thank you!
