### ISSUE TITLE
Generated tests - relationships with unique, not null columns

### ISSUE THREAD

**Issue by edoshor** [vattle/sqlboiler#160]
Using v2.4.0, generated tests allows empty values for unique, not null, columns.

Example schema:

```sql
CREATE TABLE tags (
  id          BIGSERIAL PRIMARY KEY,
  uid         CHAR(8) UNIQUE   NOT NULL,
  parent_id   BIGINT REFERENCES tags  NULL
);
```

The `testTagToOneTagUsingParent` test fails as it tries to insert both `local` and `foreign` to the DB with the same value for `uid`, i.e. the empty string `""`.

See [templates_test/relationship_to_one](https://github.com/vattle/sqlboiler/blob/master/templates_test/relationship_to_one.tpl#L15-L21)
The `canBeNull` parameter to `randomize` is always true.

**Comment by aarondl** [comment]
Forgot to push the code for this last night. Or comment on the issue. Weird :D

I believe I've solved this on dev branch.
