### ISSUE TITLE
Is it designed for 1 Database = 1 Sheme?

### ISSUE THREAD

**Issue by Venommmm** [vattle/sqlboiler#175]
i want to use sqlbolier for this situation: 1 shema and a lot of databases in the app using this shema.
I guess it can cause some problems like very large map with cached queries (as i understood sqlboiler will use same map for all databases). So is it safe to use  sqlbolier in this case?

**Comment by aarondl** [comment]
I'm not actually sure. The things that it stores in cache are relatively small. Having said that if you have enough... it could use a lot of memory. Though you seem to be implying that it using the same cache is a bad thing - but actually it'd be a good thing. There have been issues like this one https://github.com/golang/go/issues/9477 related to big maps, but I think these issues should have gone away with the GC work that was done in 1.6, 1.7 etc.

The amount of data stored is relative to number of tables, number of different queries (which columns are queried/inserted/updated). It's possible to calculate the maximum pathological amount of cache that sqlboiler could use if you have your schema. Though that calculation would take some work to get to (not too hard though).

I will say though: Nothing beats measurement. When in doubt, measure :)

**Comment by Venommmm** [comment]
Thanks for your answer:). Just last thing to clarify: for example i have 2 dbs using 1 scheme; so i make 2 equal queries to both, sqlboiler will cache them both or will have 1 cache item for both? 
Anyway, ill try slqboiler, its awesome. Just hope this  thing with large  maps and gc is in the past and wont affect perfomance.

**Comment by aarondl** [comment]
That's correct. It will re-use the cache for both of them, since the caches are package-wide (and therefore binary-wide). It will only insert two items if you connect to each database in separate binaries.

Going to close this for now. Good luck with everything :D And use the latest Go for the best GC characteristics around large maps.
