### ISSUE TITLE
support hstore and array columns?

### ISSUE THREAD

**Issue by ashb** [vattle/sqlboiler#34]
I really like the sqlboiler so far. It looks like a great project!

I searched the code base and didn't see any reference to it on master or dev branches.

I have one table which has both `hstore` and `text[]` columns. How much work would be involved in supporting these?

(I _also_ have jsonb but I see you support that on the dev branch now).

**Comment by nullbio** [comment]
I'm sure we can add support for both of these. A custom hstore type that implements Scan and Value probably won't be too difficult, and it seems the pq driver already has types for all of the array types with a GenericArray type as a fallback: https://godoc.org/github.com/lib/pq#GenericArray

**Comment by ashb** [comment]
Cool. When I'm back from holiday I might see if I have time to try a PR. (No promises though. Life and all that)

Will there be any confusion/complexity from the To Many relationship?

**Comment by nullbio** [comment]
It's okay, I've already got it covered :) It's in the dev branch if you want to take a look. We're just making making the final changes for the MySQL driver then we can release it all together.

**Comment by ashb** [comment]
Ah nice!

**Comment by nullbio** [comment]
Hi @ashb -- we've released V2 which includes the hstore and arrays mentioned above. See here for release notes: https://github.com/vattle/sqlboiler/releases/tag/v2.0.0

Thanks.

**Comment by ashb** [comment]
<3 Awesome, I'll try it out.

And :+1: for tagging releases too!

**Comment by nullbio** [comment]
Sounds good, let me know if you run into any problems :)
