### ISSUE TITLE
Feature request: Pass db object as a configuration

### ISSUE THREAD

**Issue by nguyendangminh** [vattle/sqlboiler#38]
Hi,

The _db_ object is passed repetitively, for example:
```go
err = p1.Insert(db)
pilot, err := models.PilotFind(db, 1)
pilot, err := models.Pilots(db, qm.Where("name=?", "Tim")).One()
```
Why we don't just pass the _db_ object to the _models_ package as a configuration?

**Comment by nullbio** [comment]
Hi @nguyendangminh, you can do this already. Use `boil.SetDB(db)`, and then you can use the G variant of the functions (like `models.PilotsG()` for example). The `G` variant do not take a db as a first parameter and use the global. See here: https://github.com/vattle/sqlboiler#function-variations
