### ISSUE TITLE
Slices missing InsertAll()

### ISSUE THREAD

**Issue by kris-runzer** [vattle/sqlboiler#40]
Generated slices are missing InsertAll(); it would be nice to be able to do multiple row inserts:

INSERT INTO x(col1, col2) VALUES
  ("a1", "a2"),
  ("b1", "b2"),
  ...

Not sure how that will work for the maximum query size settings for each database.  Should probably have a UpsertAll() as well?

**Comment by aarondl** [comment]
Unfortunately can't implement this. MySQL doesn't allow us to retrieve any data from a multiple-insert.
