### ISSUE TITLE
SetX fails silently for nullable foreign keys

### ISSUE THREAD

**Issue by BTBurke** [vattle/sqlboiler#44]
SetX doesn't work when you can have a nullable foreign key.  This is an easy fix and results from manually assigning the null.Int.Int value but not setting null.Int.Valid to true.

For example, in this scenario, every user might have a plan, but the foreign key `plan_id` can be null if they don't yet have a plan assigned.  So, the generated code represents `plan_id` as a `null.Int`

```sql
CREATE TYPE plan_name AS ENUM ('trial', 'small', 'medium', 'large', 'cancel', 'unpaid');

CREATE TABLE plans (
    id serial NOT NULL,
    created_at timestamp,
    updated_at timestamp,
    start timestamp NOT NULL,
    expire timestamp,
    name plan_name NOT NULL,
    user_name text NOT NULL
);

ALTER TABLE plans ADD CONSTRAINT plan_pkey PRIMARY KEY (id);

CREATE TABLE users (
    id serial NOT NULL,
    name text UNIQUE NOT NULL,
    password text NOT NULL,
    email text UNIQUE NOT NULL,
    first_name text,
    last_name text,
    plan_id integer,
    created_at timestamp,
    updated_at timestamp
);

ALTER TABLE users ADD CONSTRAINT user_pkey PRIMARY KEY (id);
ALTER TABLE users ADD CONSTRAINT plans_fkey FOREIGN KEY (plan_id) REFERENCES plans(id);
```

In the generated code, you have a `user.SetPlan()` method that is implemented like this:

```go
func (u *User) SetPlan(exec boil.Executor, insert bool, related *Plan) error {
	var err error
	if insert {
		if err = related.Insert(exec); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	oldVal := u.PlanID
	u.PlanID.Int = related.ID
       // u.PlanID.Valid = true  <========== needs this line
	if err = u.Update(exec, "plan_id"); err != nil {
		u.PlanID = oldVal
		return errors.Wrap(err, "failed to update local table")
	}
```

The generated code reaches into the `null.Int` struct to set the `Int` value directly, but does not set `Valid` to true.  This causes the subsequent update to silently fail with no error.  Should probably be using `null.IntFrom(related.ID)` rather than directly manipulating the struct values.

**Comment by aarondl** [comment]
Hey @BTBurke 

Fairly certain this was resolved in our big round of bug fixing, can you try updating to v2.0.1 and check again? I looked into this in the dev branch and it seemed to be generating the correct code now.

**Comment by BTBurke** [comment]
You're right, I forgot to upgrade to see if it fixed it.  I have a bunch of passing tests now.  Thanks!
