### ISSUE TITLE
postgres "char" is translated as string

### ISSUE THREAD

**Issue by mvdan** [vattle/sqlboiler#59]
Similar to #58, if I use a `"char"` column on postgres, this gets mapped to `string` in the generated model. Like the other issue, this isn't a dealbreaker but it would be much better to have it as `byte`. `rune` could also be used, but it's a little silly to use a 4-byte type when `"char"` in postgres is 1-byte.

**Comment by aarondl** [comment]
Going to close in favor of a continued discussion of both types in #58.
