### ISSUE TITLE
Capitalize URL to match golint

### ISSUE THREAD

**Issue by jseriff** [vattle/sqlboiler#63]
URL should be capitalized in generated names to match golint.  You can see the full list of the golint names here:

https://github.com/golang/lint/blob/3390df4df2787994aea98de825b964ac7944b817/lint.go#L731

**Comment by nullbio** [comment]
Thanks @jseriff, that's a useful list, we will make sure our list looks like this:

```
ACL, API, ASCII, CPU, EOF, GUID, ID, IP, JSON, RAM, SLA, UDP, UI, UID, UUID, URI, URL, UTF8
```

The rest should work already because they contain no vowels.

**Comment by aarondl** [comment]
https://github.com/vattle/sqlboiler/releases/tag/v2.1.0
