### ISSUE TITLE
BaseDir option not respected

### ISSUE THREAD

**Issue by pritambaral** [vattle/sqlboiler#64]
Neither setting it in the config nor passing in as cli flag works.

**Comment by nullbio** [comment]
Thank you, we'll merge this shortly along with a bunch of other things we've done in the dev branch.

**Comment by aarondl** [comment]
Fixed in d2eccc98adfeb23868f21d677963e7a2d3e095ae

**Comment by aarondl** [comment]
https://github.com/vattle/sqlboiler/releases/tag/v2.1.0
