### ISSUE TITLE
support cockroach

### ISSUE THREAD

**Issue by iven1990** [vattle/sqlboiler#68]
Do you plan to support cockroach

**Comment by nullbio** [comment]
We have no plans to support cockroachDB at the moment. My understanding is that this is a fairly new database and we'd want to see greater adoption before considering adding support for it.

**Comment by aarondl** [comment]
Keep in mind this doesn't rule out pull requests for support. It's not very hard to add a new driver now that we've done a lot of the tricky work when we added mysql support. As long as cockroach plays nicely with the basic SQL that is generated here (which it might not) and it has some way to use SQL to look up table information etc.
