### ISSUE TITLE
types.StringArray lacks import

### ISSUE THREAD

**Issue by ajankovic** [vattle/sqlboiler#78]
[importsBasedOnType](https://github.com/vattle/sqlboiler/blob/ac48562dc2ab952e2e0b7efd11c7301758d37aad/imports.go#L275) doesn't have entry for types.StringArray. This is causing build to fail due to missing import.

**Comment by nullbio** [comment]
Thanks, I've added this to the dev branch. We'll merge it into master shortly.

**Comment by nullbio** [comment]
@ajankovic I think I forgot to respond to this sorry. It's been merged into master.
