### ISSUE TITLE
Toml based configuration parameters are not working correctly

### ISSUE THREAD

**Issue by ajankovic** [vattle/sqlboiler#79]
When I specify configuration inside toml file some parameters are not picked up. When using command line arguments they are picked up.
Those that don't work for me are "schema" and "blacklist".

**Comment by nullbio** [comment]
Hi @ajankovic  Can you share your config file please. Thanks.

**Comment by aarondl** [comment]
@ajankovic Here's a patch that will enable the `--debug` flag to additionally dump the configuration. Can you please apply this patch to your sqlboiler repo and then run with `--debug` and paste the configuration output bit here in addition to your config? (You can mask the values if you want)

```go
diff --git a/sqlboiler.go b/sqlboiler.go
index 0c52dce..718dece 100644
--- a/sqlboiler.go
+++ b/sqlboiler.go
@@ -67,7 +67,12 @@ func New(config *Config) (*State, error) {
        }

        if s.Config.Debug {
-               b, err := json.Marshal(s.Tables)
+               b, err := json.Marshal(config)
+               if err != nil {
+                       return nil, errors.Wrap(err, "unable to json marshal config")
+               }
+               fmt.Printf("%s\n", b)
+               b, err = json.Marshal(s.Tables)
                if err != nil {
                        return nil, errors.Wrap(err, "unable to json marshal tables")
                }
```

**Comment by nullbio** [comment]
@ajankovic If you can also tell us what `--version` you're running that'd be great.

**Comment by nullbio** [comment]
@ajankovic I'm unable to replicate this locally. I can only presume what's happening is that you have the config lines defined underneath your database blocks in your TOML opposed to at the root level. For example, this is what it should look like:

```
blacklist=["one", "two"]
schema="myschema"
[postgres]
 host="localhost"
[mysql]
  host="localhost"
```

I'm going to close this issue, but if I'm wrong about this feel free to reopen.
