### ISSUE TITLE
Generated relationships does not have a G variant

### ISSUE THREAD

**Issue by eduacostam** [vattle/sqlboiler#87]
When setting up sqlboiler using `boil.SetDB(db)` we can use global variants of methods for accessing data instead of passing a `*sql.DB` pointer around. [Generated relationships](https://github.com/vattle/sqlboiler#relationships) between models do not have a global variant. 

What I would expect is that for each AddX, SetX, RemoveX there would be a G variant AddXG, SetXG, RemvoeXG.

As it is I started using the G variants to avoid passing an `*sql.DB` instance to all my structs, but in order to use relationships the struct must have knowledge of the DB object anyway.

**Comment by aarondl** [comment]
Hey there @eduacostam, I've corrected the issue on the dev branch and all our integration tests are passing. Can you double check to make sure everything's there that you expect and then we'll release this version of sqlboiler. Thanks!

**Comment by eduacostam** [comment]
Hey @aarondl, thanks again for the fast response and turnaround time!
I've just checked it and it seems to be as expected!
Thanks!
