### ISSUE TITLE
Eager loading fails to populate relationships on all fetched models

### ISSUE THREAD

**Issue by bjyoungblood** [vattle/sqlboiler#98]
This is easier to explain with an example.

```sql
CREATE TABLE accounts (
  id serial not null primary key,
  name text
);

CREATE TABLE transactions (
  id serial not null primary key,
  account_id int
   references accounts (id) on update cascade on delete cascade,
  description text,
  amount decimal
);

INSERT INTO accounts (id, name) VALUES
  (1, 'Account 1'),
  (2, 'Account 2'),
  (3, 'Account 3');

INSERT INTO transactions (id, account_id, description, amount) VALUES
  (1, 1, 'tx1 account 1', 1),
  (2, 1, 'tx2 account 1', 1),
  (3, 2, 'tx3 account 2', 1),
  (4, 2, 'tx4 account 1', 1),
  (5, 3, 'tx5 account 3', 1),
  (6, 2, 'tx6 account 2', 1);
```

When fetching all transactions and eager-loading the transaction's account, the result is this:

```go
transactions := models.TransactionsG(qm.Load("Account")).AllP()

transactions[0].R.Account // Account 1
transactions[1].R.Account // nil (should be Account 1)
transactions[2].R.Account // Account 2
transactions[3].R.Account // nil (should be Account 1)
transactions[4].R.Account // Account 3
transactions[5].R.Account // nil (should be Account 2)
```

I believe the solution is fairly simple, and involves switching the loop nesting between local and foreign items in a few places:

1. [To-one relationship](https://github.com/vattle/sqlboiler/blob/master/templates/07_relationship_to_one_eager.tpl#L73) - this is definitely an issue, and swapping lines 73 and 74 fixed the problem

2. [One-to-one relationship](https://github.com/vattle/sqlboiler/blob/master/templates/08_relationship_one_to_one_eager.tpl#L73) - I'm not sure if this one matters. In theory, it wouldn't if it's a perfect one-to-one relationship

3. [Many-to-many relationship](https://github.com/vattle/sqlboiler/blob/master/templates/09_relationship_to_many_eager.tpl#L120) - this also seems like it could cause the same issue, but I have yet to find an appropriate test case

I'd submit a PR to fix this, but I'm not really sure how to test.

### What version of SQLBoiler are you using (`sqlboiler --version`)?
v2.1.8 (actually, `dev`)

**Comment by aarondl** [comment]
Oh interesting. I will look at this closely tomorrow. Don't have much time for this tonight unfortunately :( Thanks for filing it!

**Comment by aarondl** [comment]
You were absolutely correct. Thank you for pointing this out. I added a little short circuiting to ensure we don't flail about when there's no results which I think was the only reason I coded the loop this way to begin with.

As for the many-to-many and to-many I think it's correct as is. I haven't tested thoroughly however. These eager loading pieces admittedly aren't tested super well and if anyone wanted to improve eager loading tests that'd be great ;)

It's on dev branch, please let me know if things are working as you expect. If you're okay with this we'll probably gear up for a minor release as many things have changed in the dev branch. :) Thanks again.

**Comment by bjyoungblood** [comment]
Dev branch looks to be working great!

**Comment by zwf** [comment]
hi @aarondl , thank you for your great work on SQLBolier. We are using SQLBoiler and faced this bug too, we want to know the schedule of fixing this, so we can make a decision on using SQLBoiler on production server. Thank you very much.

**Comment by aarondl** [comment]
Hey there @zwf, this bug is already fixed in the dev branch. We're working towards a release with this last set of fixes. I know it's been a long time coming and I apologize for that. The dev branch should land soon (this week).

**Comment by zwf** [comment]
Great 👍 ! Thank you very much.
